# Generated by Django 6.0.1 on 2026-01-21 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_likes_alter_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='product',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
