# Generated by Django 6.0.1 on 2026-01-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per hour or per acre', max_digits=10)),
                ('provider_name', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Link to a service image')),
            ],
        ),
    ]
