# Generated by Django 6.0.1 on 2026-01-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('pest', 'Pest Control'), ('irrigation', 'Irrigation Setup'), ('rental', 'Equipment Rental'), ('consult', 'Fertilizer Consultation')], default='pest', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
    ]
